server:
  port: 8055 # 服务端口

spring:
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/localdata?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   #swagger2，springboot2.6版本以上要加
  mail:
    host: smtp.qq.com
    username: 28*****99@qq.com
    password: ki*********ja

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/**/*.xml


logging:
  level:
    - com.trace.core: debug


aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    keyId: LT*************zj
    keySecret: iym*************kE8
    bucketName: t*********t
